import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useMerge } from "@nap5/use-merge";
import { useClude } from "@nap5/use-clude";
import { z } from "zod";
import data from "../data/bebop.json";
const userShape = {
  id: z.string(),
  name: z.string(),
  age: z.number(),
  blogs: z
    .object({
      id: z.string(),
      title: z.string(),
    })
    .array(),
};

const Home: NextPage = () => {
  const { merge } = useMerge();
  const { include, exclude } = useClude(userShape);
  console.log(
    JSON.stringify(
      data.map((item) => include("blogs").parse(item)),
      null,
      2
    )
  );
  console.log(
    JSON.stringify(
      data.map((item) => exclude("name", "age").parse(item)),
      null,
      2
    )
  );
  const obj1 = {
    a: null,
    b: "BBB",
    c: {
      "c-1": "CCC",
    },
    d: {
      "d-1": null,
      "d-2": null,
      "d-3": null,
    },
  };
  const obj2 = {
    a: "AAA",
    b: null,
    c: {
      "c-1": null,
    },
    d: {
      "d-1": null,
      "d-2": "DDD-2",
      "d-3": null,
    },
  };

  const obj3 = {
    d: {
      "d-1": "DDD-1",
      "d-3": "DDD-3",
    },
  };

  console.log(merge(obj1, obj2, obj3));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
